stages:
  - build
  - test

# Build stage to compile the Next.js application
build:
  image: node:23.7  # You can adjust the Node version if needed
  stage: build]
  before_script: 
    - cd sakura-flashcardsnpm
    - npm install 
    - webdriver-manager update
    - npm run build
  script:
    - npm run test   # Run Jest tests
  cache:
    paths:
      - node_modules/  # Cache node_modules to speed up subsequent builds
      - .next/cache/

# Test stage to run Jest tests
test:
  image: node:23.7  # Make sure to use the same Node.js version as in the build stage
  stage: test
  before_script:
    - cd sakura-flashcards
    - npm install  # Install dependencies
    - webdriver-manager update
  script:
    - npm run test   # Run Jest tests
  artifacts:
    paths:
      - coverage/  # Optionally store coverage results if needed
  cache:
    paths:
      - node_modules/  # Cache node_modules to speed up subsequent builds
      - .next/cache/
