stages:
  - build

# Build stage to compile the Next.js application
build:
  image: node:23.7  # You can adjust the Node version if needed
  stage: build]
  before_script: 
    - cd sakura-flashcardsnpm
    - npm install 
    - webdriver-manager update
    - npm run build
  script:
    - npm run test   # Run Jest tests
  cache:
    paths:
      - node_modules/  # Cache node_modules to speed up subsequent builds
      - .next/cache/
