stages:
  - build
  - test

# Build stage to compile the Next.js application
build:
  image: node:23.7  # You can adjust the Node version if needed
  stage: build
  before_script:
    - cd sakura-flashcards
    - npm install  # Install dependencies
    - npm run build  # Run the next build command to build your Next.js app
  script:
    - npm run dev
  cache:
    paths:
      - node_modules/  # Cache node_modules to speed up subsequent builds

# Test stage to run Jest tests
test:
  image: node:23.7  # Make sure to use the same Node.js version as in the build stage
  stage: test
  before_script:
    - cd sakura-flashcards
    - npm install  # Install dependencies (ensure all dependencies are installed)
    - npm run build  # Ensure the app is built before running tests
  script:
    - npm run test   # Run Jest tests
  artifacts:
    paths:
      - coverage/  # Optionally store coverage results if needed
  cache:
    paths:
      - node_modules/  # Cache node_modules to speed up subsequent builds
